services:
  node:
    image: node:20.11.1-alpine
    command: npm run dev
    user: node
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080