# by touch4it
services:
  node:
    image: node:20.11.1-alpine
    command: npm run dev
    user: node
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
  mongo:
    image: mongo:5.0.25
    ports:
      - 27018:27017
#